version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor  # Preserve Composer dependencies
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=clms_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network
    command: >
      sh -c "if [ ! -f .env ]; then cp .env.example .env; fi && \
             until mysqladmin ping -h\"$DB_HOST\" -u\"$DB_USERNAME\" -p\"$DB_PASSWORD\" --silent; do \
               echo 'Waiting for database...'; \
               sleep 3; \
             done && \
             php artisan key:generate --force && \
             php artisan migrate --force && \
             php artisan db:seed --force && \
             php artisan config:cache && \
             apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clms_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - laravel_network

volumes:
  dbdata:
    driver: local
  vendor:
    driver: local

networks:
  laravel_network:
    driver: bridge